debug: false

logging:
  level:
    ROOT: WARN
    org.springframework: INFO  # TEMPORARY
    org.hibernate.SQL: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://store-db:5432/store
    password: ${DB_ROOT_PASS}
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: http://zipkin.monitoring:9411/
  kafka:
    consumer:
      bootstrap-servers: kafka.default:9092


client:
  url: https://www.dh4r4pvj.ga
