debug: false

logging:
  level:
    ROOT: WARN
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://store-db:5432/store
    password: ${DB_ROOT_PASS}
    username: postgres
    driver-class-name: org.postgresql.Driver
    # Only for demo purpose... below setting will pickup schema.sql and data.sql and execute them
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: http://zipkin.monitoring:9411/
  kafka:
    consumer:
      bootstrap-servers: kafka.default:9092


client:
  url: https://www.dh4r4pvj.ga
