debug: true

server: 
  port: 8081
  servlet: 
    context-path: /

logging:
  level:
    ROOT: INFO
    com.kubewarrior: DEBUG
    org.springframework.security: DEBUG
    org.springframework: DEBUG

spring:
  data:
    rest:
      defaultMediaType: "application/json"
  application:
    name: store
    sleuth:
      sampler:
        percentage: 1
      zipkin:
        base-url: http://localhost:9411/
  jpa:
    hibernate:
# marked as none so that schema.sql can create the schema for now
      ddl-auto: none

  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

#   security:
#     oauth2:
#       resourceserver:
#         jwt:
#           issuer-uri: http://localhost:9080/auth/realms/micro-auth
#           jwk-set-uri: http://localhost:9080/auth/realms/micro-auth/protocol/openid-connect/certs