debug: false

logging:
  level:
    ROOT: WARN
    org.springframework.web: TRACE

spring:
  datasource:
    url: jdbc:mariadb://store-db:3306/store
    password: ${DB_ROOT_PASS}

client:
  url: http://dh4r4pvj.ga
