server: 
  port: 8081
  servlet: 
    context-path: /

logging:
  level:
    ROOT: DEBUG
    com.kubewarrior: DEBUG
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/auth/realms/micro-auth
          jwk-set-uri: http://localhost:9080/auth/realms/micro-auth/protocol/openid-connect/certs